spring.application.name=Execice_ticket_emailnotification

# 1. URL de la base de données (on pointe vers la base "training" que vous avez core)
spring.datasource.url=jdbc:mysql://localhost:3306/ticket_budget

# 2. Identifiers
spring.datasource.username=root
spring.datasource.password=09152T049t@

# 3. Driver MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 4. Configuration Hibernate / JPA
# "update" permet de crier ou modifier les tables automaticities salon vos classes @Entity
spring.jpa.hibernate.ddl-auto=update

# Affiche les requêtes SQL dans la console (très utile pour débugger)
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=savadogoibrahim0915@gmail.com
spring.mail.password=pavf wggs fgpz mjua
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

